package LoginServer::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'LoginServer::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:oauth2_server',
        user => 'oauth2_server',
        password => 'set-this-in-loginserver.yml',
        # This is important because otherwise some bad SQL is generated
        quote_names => 1,
    }
);

=head1 NAME

LoginServer::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<LoginServer>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<LoginServer::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
